beers_style = [
    "Altbier",
    "Alternative Grain Beer",
    "Alternative Sugar Beer",
    "American Amber Ale",
    "American Barleywine",
    "American Brown Ale",
    "American IPA",
    "American Lager",
    "American Light Lager",
    "American Pale Ale",
    "American Porter",
    "American Stout",
    "American Strong Ale",
    "American Wheat Beer",
    "American Wheat or Rye Beer",
    "Apple Wine",
    "Australian Sparkling Ale",
    "Autumn Seasonal Beer",
    "Baltic Porter",
    "Belgian Blond Ale",
    "Belgian Dark Strong Ale",
    "Belgian Dubbel",
    "Belgian Golden Strong Ale",
    "Belgian Pale Ale",
    "Belgian Specialty Ale",
    "Belgian Tripel",
    "Berliner Weisse",
    "Best Bitter",
    "Bière de Garde",
    "Blonde Ale",
    "Bohemian Pilsener",
    "Braggot",
    "Brett Beer",
    "British Brown Ale",
    "British Golden Ale",
    "British Strong Ale",
    "Brown Porter",
    "California Common",
    "California Common Beer",
    "Classic American Pilsner",
    "Classic Rauchbier",
    "Classic Style Smoked Beer",
    "Clone Beer",
    "Common Cider",
    "Cream Ale",
    "Cyser (Apple Melomel)",
    "Czech Amber Lager",
    "Czech Dark Lager",
    "Czech Pale Lager",
    "Czech Premium Pale Lager",
    "Dusseldorf Altbier",
    "Dark American Lager",
    "Dark Mild",
    "Doppelbock",
    "Dortmunder Export",
    "Double IPA",
    "Dry Mead",
    "Dry Stout",
    "Dunkelweizen",
    "Dunkles Bock",
    "Dunkles Weissbier",
    "Eisbock",
    "English Barleywine",
    "English Cider",
    "English IPA",
    "English Porter",
    "Experimental Beer",
    "Extra Special/Strong Bitter (ESB)",
    "Festbier",
    "Flanders Brown Ale/Oud Bruin",
    "Flanders Red Ale",
    "Foreign Extra Stout",
    "French Cider",
    "Fruit and Spice Beer",
    "Fruit Beer",
    "Fruit Cider",
    "Fruit Lambic",
    "German Helles Exportbier",
    "German Leichtbier",
    "German Pils",
    "German Pilsner (Pils)",
    "Gose",
    "Gueuze",
    "Helles Bock",
    "Holiday/Winter Special Spiced Beer",
    "Imperial IPA",
    "Imperial Stout",
    "International Amber Lager",
    "International Dark Lager",
    "International Pale Lager",
    "Irish Extra Stout",
    "Irish Red Ale",
    "Irish Stout",
    "Kölsch",
    "Kellerbier: Amber Kellerbier",
    "Kellerbier: Pale Kellerbier",
    "Kentucky Common",
    "Lambic",
    "Lichtenhainer",
    "Light American Lager",
    "London Brown Ale",
    "Märzen",
    "Maibock/Helles Bock",
    "Metheglin",
    "Mild",
    "Mixed-Fermentation Sour Beer",
    "Mixed-Style Beer",
    "Munich Dunkel",
    "Munich Helles",
    "New England Cider",
    "nan",
    "North German Altbier",
    "Northern English Brown",
    "Oatmeal Stout",
    "Oktoberfest/Märzen",
    "Old Ale",
    "Open Category Mead",
    "Ordinary Bitter",
    "Other Fruit Melomel",
    "Other Smoked Beer",
    "Other Specialty Cider or Perry",
    "Oud Bruin",
    "Piwo Grodziskie",
    "Premium American Lager",
    "Pre-Prohibition Lager",
    "Pre-Prohibition Porter",
    "Pyment (Grape Melomel)",
    "Rauchbier",
    "Robust Porter",
    "Roggenbier",
    "Roggenbier (German Rye Beer)",
    "Russian Imperial Stout",
    "Sahti",
    "Saison",
    "Schwarzbier",
    "Scottish Export",
    "Scottish Export 80/-",
    "Scottish Heavy",
    "Scottish Heavy 70/-",
    "Scottish Light",
    "Scottish Light 60/-",
    "Semi-Sweet Mead",
    "Southern English Brown",
    "Special/Best/Premium Bitter",
    "Specialty Beer",
    "Specialty Fruit Beer",
    "Specialty IPA: Belgian IPA",
    "Specialty IPA: Black IPA",
    "Specialty IPA: Brown IPA",
    "Specialty IPA: Red IPA",
    "Specialty IPA: Rye IPA",
    "Specialty IPA: White IPA",
    "Specialty Smoked Beer",
    "Specialty Wood-Aged Beer",
    "Spice  Herb  or Vegetable Beer",
    "Standard American Lager",
    "Standard/Ordinary Bitter",
    "Straight (Unblended) Lambic",
    "Strong Bitter",
    "Strong Scotch Ale",
    "Sweet Mead",
    "Traditional Bock",
    "Traditional Perry",
    "Trappist Single",
    "Tropical Stout",
    "Vienna Lager",
    "Wee Heavy",
    "Weissbier",
    "Weizen/Weissbier",
    "Weizenbock",
    "Wheatwine",
    "Wild Specialty Beer",
    "Winter Seasonal Beer",
    "Witbier",
    "Wood-Aged Beer",
]
